"""empty message

Revision ID: 18298f1ad2a4
Revises: a0c728eef362
Create Date: 2023-05-19 18:50:24.427758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18298f1ad2a4'
down_revision = 'a0c728eef362'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('level_problem')
    op.drop_table('problem_24hr')
    op.drop_table('UnsolvedProblem')
    op.drop_table('problem')
    op.alter_column('rank', 'hufs_rank',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('unsolved_problem', 'problem_num',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('unsolved_problem', 'problem_lev',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('unsolved_problem', 'problem_link',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('unsolved_problem', 'problem_challengers',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_unsolved_problem_problem_title'), 'unsolved_problem', ['problem_title'], unique=False)
    op.add_column('user', sa.Column('user_id', sa.String(length=255), nullable=False))
    op.add_column('user', sa.Column('user_pw', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('user_name', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('user_solved_count', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('user_baekjoon_id', sa.String(length=255), nullable=False))
    op.add_column('user', sa.Column('user_rank', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_user_user_name'), 'user', ['user_name'], unique=False)
    op.create_index(op.f('ix_user_user_pw'), 'user', ['user_pw'], unique=False)
    op.drop_column('user', 'solved')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.TEXT(), nullable=True))
    op.add_column('user', sa.Column('solved', sa.INTEGER(), nullable=True))
    op.drop_index(op.f('ix_user_user_pw'), table_name='user')
    op.drop_index(op.f('ix_user_user_name'), table_name='user')
    op.drop_column('user', 'user_rank')
    op.drop_column('user', 'user_baekjoon_id')
    op.drop_column('user', 'user_solved_count')
    op.drop_column('user', 'user_name')
    op.drop_column('user', 'user_pw')
    op.drop_column('user', 'user_id')
    op.drop_index(op.f('ix_unsolved_problem_problem_title'), table_name='unsolved_problem')
    op.alter_column('unsolved_problem', 'problem_challengers',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('unsolved_problem', 'problem_link',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('unsolved_problem', 'problem_lev',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('unsolved_problem', 'problem_num',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('rank', 'hufs_rank',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.create_table('problem',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('UnsolvedProblem',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('problem_num', sa.INTEGER(), nullable=False),
    sa.Column('problem_lev', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('problem_24hr',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('level_problem',
    sa.Column('level', sa.INTEGER(), nullable=True),
    sa.Column('count', sa.INTEGER(), nullable=True),
    sa.Column('problem_data', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('level')
    )
    # ### end Alembic commands ###
