"""empty message

Revision ID: a0c728eef362
Revises: 
Create Date: 2023-05-02 01:07:48.771459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0c728eef362'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UnsolvedProblem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_num', sa.Integer(), nullable=False),
    sa.Column('problem_lev', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UnsolvedProblem')
    # ### end Alembic commands ###
